"""Regenerate FIGURES.md (figure index) from the image/caption pairs of MANUSCRIPT_EN.md and SUPPLEMENTARY_EN.md."""
import re
from pathlib import Path
SRC = Path(__file__).resolve().parent.parent
pat = re.compile(r'^!\[([^\]]*)\]\((figures/[^)]+)\)\s*\n\s*\n(\*\*(?:Figure|Fig\.) [^\n]+)\n', re.M)
out = ['# Figures', '', 'Index of the figures in the manuscript and the supplementary material (generated by latex/gen_figures_md.py; captions as in the text). Each figure is available as PNG and PDF in `figures/`.', '']
for name, title in (('MANUSCRIPT_EN.md', 'Main text'), ('SUPPLEMENTARY_EN.md', 'Supplementary material')):
    out += ['## ' + title, '']
    for m in pat.finditer((SRC / name).read_text()):
        path = m.group(2); pdf = re.sub(r'\.png$', '.pdf', path)
        links = f'[PNG]({path})' + (f' · [PDF]({pdf})' if (SRC / pdf).exists() else '')
        out += [f'### {m.group(1)}', '', f'![{m.group(1)}]({path})', '', m.group(3), '', links, '']
(SRC / 'FIGURES.md').write_text('\n'.join(out))
print(sum(1 for l in out if l.startswith('### ')), 'figures')
