"""V1: geometry-conditioned two-scale super-element, trained across FULL labels.

  S_hat(theta) = L_GG^T (I + M M^T)^-1 L_GG
  L_GG : banded factor on the fine face grid, entries generated by a pair head from face-CNN node features
  M    : k dense softening columns generated per DOF by a mode head
Loss: teacher energy metric on physical probes + isotropic action term (same as V0). Labels rotate in chunks.
"""
import argparse, glob, json, math, os, sys, time
import numpy as np, torch
from torch import nn
from torch.nn import functional as F
sys.path.insert(0, '/root/cutfem_neural_a_20260910/source_14301bc56'); sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import v0_superelement as V0
from stage_cutfem_neural_a.data import load_teacher_dense, write_json
from stage_cutfem_neural_a.dense_fit import FactorSample, make_directions, json_finite
from stage_cutfem_neural_a.dense_row_fit import append_json
from stage_cutfem_neural_a.elimination_reference import DenseUpperFactor, load_upper_factor, quotient_dense, evaluate

torch.backends.cuda.matmul.allow_tf32 = False; torch.backends.cudnn.allow_tf32 = False
DEV = torch.device('cuda'); N = 65
S0 = 0.01          # geometry-only stiffness unit (S_ii ~ 0.01 w on 0415)
OFF_SCALE = 10.0   # default bound of |L_ij| relative to min(L_ii, L_jj) times the distance prior; overridden by --off-scale
DEPTHS = (0, 1, 2, 4)


def sync():
    torch.cuda.synchronize(); return time.perf_counter()


# ----------------------------------------------------------------------------- label container
class Label:
    def __init__(self, record, r_near, decay, off_scale, coarse_stride=4):
        self.record = record; self.seat = int(record['seat'])
        self.sample = FactorSample(record, 2026091197); self.data = self.sample.data; cache = self.sample.cache
        assert np.all(np.diff(cache['indptr']) == 1) and np.allclose(cache['coefficients'], 1.0), 'nodal trace functionals required'
        self.ijk = np.stack(np.unravel_index(cache['background_nodes'][cache['indices']], (N, N, N)), axis=1)
        self.nn = len(self.ijk); self.q = 3 * self.nn; self.d = self.data.dimension
        assert self.d == self.q - 6
        self.w = np.clip(V0.support_weights(self.ijk, N, cache['tau_corners'], cache['cut_plane']), 1e-4, 1.0)
        self.wq = torch.from_numpy(self.w).double().repeat_interleave(3)
        self.P3 = torch.from_numpy(np.kron(V0.coarse_interpolation(self.ijk, N, coarse_stride), np.eye(3)))
        self.theta = torch.from_numpy(np.concatenate((cache['tau_corners'], cache['cut_plane']))).float()
        # face membership of every node (edges/corners belong to several faces)
        mem = []
        for f in range(6):
            ax, side = f // 2, f % 2; on = np.nonzero(self.ijk[:, ax] == (0 if side == 0 else N - 1))[0]
            free = [a for a in range(3) if a != ax]
            for i in on: mem.append((i, f, self.ijk[i, free[0]], self.ijk[i, free[1]]))
        mem = np.array(mem); self.mem_node = torch.from_numpy(mem[:, 0]); self.mem_face = torch.from_numpy(mem[:, 1])
        self.mem_pix = torch.from_numpy(mem[:, 2] * N + mem[:, 3]); self.face_of_node = torch.from_numpy(V0.face_ids(self.ijk, N))
        # face images: analytic channels at several depths, node mask, support weight, in-plane coordinates, face one-hot
        grid = self.data.grid[0].numpy()                                   # (11, 65, 65, 65)
        imgs = []
        for f in range(6):
            ax, side = f // 2, f % 2; free = [a for a in range(3) if a != ax]
            ch = []
            for dep in DEPTHS:
                p = dep if side == 0 else N - 1 - dep
                sl = np.take(grid, p, axis=1 + ax)                         # (11, 65, 65) in ascending free axes
                ch.append(sl)
            mask = np.zeros((N, N)); wimg = np.zeros((N, N))
            sel = mem[mem[:, 1] == f]; mask[sel[:, 2], sel[:, 3]] = 1.0; wimg[sel[:, 2], sel[:, 3]] = self.w[sel[:, 0]]
            uu, vv = np.meshgrid(np.linspace(0, 1, N), np.linspace(0, 1, N), indexing='ij')
            onehot = np.zeros((6, N, N)); onehot[f] = 1.0
            imgs.append(np.concatenate(ch + [mask[None], wimg[None], uu[None], vv[None], onehot], axis=0))
        self.images = torch.from_numpy(np.stack(imgs)).float()            # (6, C_in, 65, 65)
        # near-field node pairs and the sorted DOF band
        xyz = torch.from_numpy(self.ijk / (N - 1)).to(DEV).double()
        ni, nj = V0.pairs_within(xyz, xyz, r_near, upper=True)
        off = ni != nj; pi, pj = ni[off], nj[off]
        self.pair_i, self.pair_j = pi.cpu(), pj.cpu()
        dvec = (xyz[pj] - xyz[pi]); self.pair_dx = dvec.float().cpu(); dist = torch.linalg.vector_norm(dvec, dim=1)
        self.pair_decay = torch.exp(-dist / decay).cpu()
        # DOF entries: off-diagonal blocks (9 per pair) and diagonal blocks (6 per node)
        a = torch.arange(3); npair = len(pi)
        I_off = (pi[:, None, None] * 3 + a[None, :, None].to(DEV)).expand(-1, 3, 3).reshape(-1)
        J_off = (pj[:, None, None] * 3 + a[None, None, :].to(DEV)).expand(-1, 3, 3).reshape(-1)
        node = torch.arange(self.nn, device=DEV); ua, ub = torch.triu_indices(3, 3)
        I_dg = (node[:, None] * 3 + ua[None, :].to(DEV)).reshape(-1); J_dg = (node[:, None] * 3 + ub[None, :].to(DEV)).reshape(-1)
        I = torch.cat((I_off, I_dg)); J = torch.cat((J_off, J_dg))
        order = torch.argsort(I * self.q + J)
        self.band_index = torch.stack((I[order], J[order])).cpu(); self.band_index_t = torch.stack((J[order], I[order])).cpu()
        self.band_perm = order.cpu()                                       # position in [off entries (npair*9) | diag entries (nn*6)]
        self.n_off_entries = npair * 9
        self.dirs = None                                                   # evaluation directions, built lazily on GPU

    def to_gpu(self):
        g = dict(images=self.images.to(DEV), theta=self.theta.to(DEV), mem_node=self.mem_node.to(DEV), mem_face=self.mem_face.to(DEV), mem_pix=self.mem_pix.to(DEV),
                 face_of_node=self.face_of_node.to(DEV), pair_i=self.pair_i.to(DEV), pair_j=self.pair_j.to(DEV), pair_dx=self.pair_dx.to(DEV), pair_decay=self.pair_decay.to(DEV),
                 band_index=self.band_index.to(DEV), band_index_t=self.band_index_t.to(DEV), band_perm=self.band_perm.to(DEV), wq=self.wq.to(DEV), P3=self.P3.to(DEV),
                 w=torch.from_numpy(self.w).double().to(DEV))
        data = self.data.cuda()
        S, _ = load_teacher_dense(self.record['packet'], data.quotient.dimension, DEV)
        A, _ = quotient_dense(S, data.quotient); del S
        Rstar = load_upper_factor(Path(self.record['reference']) / 'R_UPPER.npy', self.d, DEV)
        g.update(data=data, A=A, Rstar=Rstar, rigid=torch.from_numpy(self.sample.cache['rigid']).to(DEV).double())
        return g

    def release(self):
        self.data = self.data.cpu(); torch.cuda.empty_cache()


from pathlib import Path


# ----------------------------------------------------------------------------- network
class ResBlock(nn.Module):
    def __init__(self, c, dilation):
        super().__init__()
        self.c1 = nn.Conv2d(c, c, 3, padding=dilation, dilation=dilation); self.c2 = nn.Conv2d(c, c, 3, padding=1)
        self.norm = nn.GroupNorm(8, c)
    def forward(self, x):
        return x + self.c2(F.silu(self.c1(F.silu(self.norm(x)))))


class GeometryNet(nn.Module):
    def __init__(self, c_in, width=64, rank=512, hidden=128, dilations=(1, 2, 4, 8), off_scale=OFF_SCALE):
        super().__init__()
        self.width, self.rank, self.off_scale = width, rank, off_scale
        self.stem = nn.Conv2d(c_in, width, 3, padding=1)
        self.blocks = nn.ModuleList([ResBlock(width, dl) for dl in dilations])
        self.context = nn.Sequential(nn.Linear(width + 12, width), nn.SiLU(), nn.Linear(width, width))
        self.node_norm = nn.LayerNorm(width)
        self.diag = nn.Sequential(nn.Linear(width, hidden), nn.SiLU(), nn.Linear(hidden, 6))          # 3 log-diag corrections + 3 in-block off values
        self.pair = nn.Sequential(nn.Linear(2 * width + 4 + 12, hidden), nn.SiLU(), nn.Linear(hidden, hidden), nn.SiLU(), nn.Linear(hidden, 9))
        self.mode = nn.Sequential(nn.Linear(width, hidden), nn.SiLU(), nn.Linear(hidden, 3 * rank))
        self.mode_logscale = nn.Parameter(torch.full((rank,), math.log(0.03)))
        for head in (self.diag, self.pair, self.mode):
            nn.init.normal_(head[-1].weight, std=1e-2); nn.init.zeros_(head[-1].bias)

    def node_features(self, g):
        x = self.stem(g['images'])
        for b in self.blocks: x = b(x)
        ctx = self.context(torch.cat((x.mean(dim=(0, 2, 3)), g['theta'])))
        flat = x.flatten(2)                                                  # (6, C, 65*65)
        feats = flat[g['mem_face'], :, g['mem_pix']]                         # (memberships, C)
        n = int(g['face_of_node'].shape[0])
        h = torch.zeros((n, self.width), device=DEV, dtype=feats.dtype).index_add_(0, g['mem_node'], feats)
        cnt = torch.zeros(n, device=DEV, dtype=feats.dtype).index_add_(0, g['mem_node'], torch.ones_like(feats[:, 0]))
        return self.node_norm(h / cnt[:, None] + ctx[None, :])

    def forward(self, g, log_w):
        """Returns band COO values (sorted order, float64) and M (q x rank, float64).
        Off-diagonal band entries are bounded by the smaller of the two diagonals they connect, times a distance prior,
        so every row of L stays within a bounded ratio of its diagonal and the triangular solves stay stable."""
        h = self.node_features(g); n = h.shape[0]
        dg = self.diag(h)                                                    # (n, 6)
        logdiag = math.log(S0) * 0.5 + 0.5 * log_w[:, None] + 3.0 * torch.tanh(dg[:, :3] / 3.0).double()   # bounded log correction (+-3)
        D = logdiag.exp()                                                    # (n, 3)
        ua, ub = torch.triu_indices(3, 3, device=DEV); is_d = ua == ub
        dmin_in = torch.minimum(D[:, ua[~is_d]], D[:, ub[~is_d]])            # (n, 3) in-block pairs (0,1),(0,2),(1,2)
        dvals = torch.empty((n, 6), dtype=torch.float64, device=DEV)
        dvals[:, is_d] = D; dvals[:, ~is_d] = self.off_scale * dmin_in * torch.tanh(dg[:, 3:]).double()
        fi = F.one_hot(g['face_of_node'], 6).float()
        pi, pj = g['pair_i'], g['pair_j']
        inp = torch.cat((h[pi], h[pj], 5.0 * g['pair_dx'], (g['face_of_node'][pi] == g['face_of_node'][pj]).float()[:, None], fi[pi], fi[pj]), dim=1)
        dmin = torch.minimum(D[pi][:, :, None], D[pj][:, None, :]).reshape(-1, 9)      # (npair, 9)
        blocks = torch.tanh(self.pair(inp)).double() * dmin * (self.off_scale * g['pair_decay'])[:, None]
        values = torch.cat((blocks.reshape(-1), dvals.reshape(-1)))[g['band_perm']]
        M = (0.1 * torch.tanh(self.mode(h))).double().view(-1, self.rank) * self.mode_logscale.exp().double()[None, :]      # (q, rank), bounded entries
        return values, M


class BandTriSolve(torch.autograd.Function):
    """Solve L X = B (upper=True) or L^T X = B (upper=False) for a banded upper-triangular L given by COO (index, values).
    Backward computes the gradient only on the band, never a dense q x q gradient; the dense L is rebuilt in backward."""
    @staticmethod
    def forward(ctx, values, B, index, q, upper):
        L = torch.sparse_coo_tensor(index, values.detach(), (q, q), is_coalesced=True).to_dense()
        X = torch.linalg.solve_triangular(L if upper else L.T, B, upper=upper); del L
        ctx.save_for_backward(values.detach(), X, index); ctx.q, ctx.upper = q, upper
        return X
    @staticmethod
    def backward(ctx, dX):
        values, X, index = ctx.saved_tensors; q, upper = ctx.q, ctx.upper
        L = torch.sparse_coo_tensor(index, values, (q, q), is_coalesced=True).to_dense()
        # X = L^-1 B:  dB = L^-T dX,  dL[i,j] = -(L^-T dX)_i . X_j ;   X = L^-T B:  dB = L^-1 dX,  dL[i,j] = -X_i . (L^-1 dX)_j
        Y = torch.linalg.solve_triangular(L.T if upper else L, dX, upper=not upper); del L
        I, J = index[0], index[1]; g = torch.empty(I.shape[0], dtype=values.dtype, device=values.device)
        for b in range(0, I.shape[0], 2_000_000):
            i, j = I[b:b + 2_000_000], J[b:b + 2_000_000]
            g[b:b + 2_000_000] = -((Y[i] * X[j]).sum(1) if upper else (X[i] * Y[j]).sum(1))
        return g, Y, None, None, None


class Operator:
    """S_hat = L^T (I + M M^T)^-1 L, applied by Woodbury with G = I + M^T M."""
    def __init__(self, g, values, M):
        self.q = int(M.shape[0]); self.values = values; self.index = g['band_index']
        self.L = torch.sparse_coo_tensor(g['band_index'], values, (self.q, self.q), is_coalesced=True)
        self.LT = torch.sparse_coo_tensor(g['band_index_t'], values, (self.q, self.q)); self.M = M
        G = M.T @ M; G.diagonal().add_(1.0); self.C = torch.linalg.cholesky(G)
    def apply(self, x):
        u = torch.sparse.mm(self.L, x); t = self.M.T @ u
        u = u - self.M @ torch.cholesky_solve(t, self.C)
        return torch.sparse.mm(self.LT, u)
    def restricted_inverse(self, quotient, rigid, y):
        """x_hat = (B S_hat B^T)^-1 y via full-space solves S_hat^-1 = L^-1 (I + M M^T) L^-T and a rank-6 rigid correction."""
        Fm = torch.cat((quotient.lift(y), rigid), dim=1)
        Z = BandTriSolve.apply(self.values, Fm, self.index, self.q, False); Z = Z + self.M @ (self.M.T @ Z)
        U = BandTriSolve.apply(self.values, Z, self.index, self.q, True); m = y.shape[1]; UF, UN = U[:, :m], U[:, m:]
        return quotient(UF - UN @ torch.linalg.solve(rigid.T @ UN, rigid.T @ UF))
    @torch.no_grad()
    def materialize(self):
        Y = torch.linalg.solve_triangular(self.C, self.M.T, upper=False)
        T = -(Y.T @ Y); del Y; T.diagonal().add_(1.0)
        Q1 = torch.sparse.mm(self.LT, T); del T
        S = torch.sparse.mm(self.LT, Q1.T.contiguous()); del Q1
        return 0.5 * (S + S.T)


# ----------------------------------------------------------------------------- probes, loss, evaluation
def draw_probes(g, m, white, generator):
    q, d = g['P3'].shape[0], g['A'].shape[0]; mc = m // 2
    zc = torch.randn(g['P3'].shape[1], mc, dtype=torch.float64, device=DEV, generator=generator)
    xf = torch.randn(q, m - mc, dtype=torch.float64, device=DEV, generator=generator) * g['wq'].sqrt()[:, None]
    z = g['data'].quotient(torch.cat((g['P3'] @ zc, xf), dim=1))
    if white:
        xi = torch.randn(d, white, dtype=torch.float64, device=DEV, generator=generator)
        z = torch.cat((z, torch.linalg.solve_triangular(g['Rstar'], xi, upper=True)), dim=1)
    return z


def energy_error(g, op, z):
    ref = g['A'] @ z; pred = g['data'].quotient(op.apply(g['data'].quotient.lift(z)))
    return torch.linalg.solve_triangular(g['Rstar'].T, pred - ref, upper=False).square().sum(0) / (g['Rstar'] @ z).square().sum(0)


def dual_error(g, op, m, generator):
    xi = torch.randn(g['A'].shape[0], m, dtype=torch.float64, device=DEV, generator=generator)
    xh = op.restricted_inverse(g['data'].quotient, g['rigid'], g['Rstar'].T @ xi)
    return (g['Rstar'] @ xh - xi).square().sum(0) / xi.square().sum(0)


def action_error(g, op, z):
    ref = g['A'] @ z; pred = g['data'].quotient(op.apply(g['data'].quotient.lift(z)))
    return (pred - ref).square().sum(0) / ref.square().sum(0)


@torch.no_grad()
def evaluate_label(label, g, net, seed):
    tick = sync()
    values, M = net(g, g['w'].log()); op = Operator(g, values, M)
    held = draw_probes(g, 64, 32, torch.Generator(device=DEV).manual_seed(seed + 2))
    e = energy_error(g, op, held)
    res = dict(seat=label.seat, q=label.q, held_energy_error=float(e[:64].mean()), held_coarse=float(e[:32].mean()), held_fine=float(e[32:64].mean()), held_white=float(e[64:].mean()),
               held_dual=float(dual_error(g, op, 32, torch.Generator(device=DEV).manual_seed(seed + 4)).mean()))
    A, R = g['A'], g['Rstar']
    Shat = op.materialize(); Ahat, _ = quotient_dense(Shat, g['data'].quotient); del Shat
    _, info = torch.linalg.cholesky_ex(Ahat, upper=True); res['cholesky_info'] = int(info)
    D = Ahat - A; res['schur_relative_error'] = float(torch.linalg.vector_norm(D) / torch.linalg.vector_norm(A))
    off = D.clone(); off.diagonal().zero_(); Aoff = A.clone(); Aoff.diagonal().zero_()
    res['offdiagonal_relative_error'] = float(torch.linalg.vector_norm(off) / torch.linalg.vector_norm(Aoff)); del off, Aoff, D
    fac = V0.LUFactor(Ahat)
    if label.dirs is None:
        x, names, force = make_directions(label.data, label.sample.cache); label.dirs = (x, names, force, DenseUpperFactor(R).solve(force))
    x, names, force, fref = label.dirs
    mech = evaluate(fac, lambda v: A @ v, x, names, force, fref)
    res['groups'] = mech['groups']; res['independent_force_summary'] = mech['independent_force_summary']
    def en(xm, xr): return torch.linalg.vector_norm(R @ (xm - xr), dim=0) / torch.linalg.vector_norm(R @ xr, dim=0)
    e_inv = en(fac.solve(A @ x), x)
    res['inverse_energy_norm_rms'] = {grp: float(e_inv[[i for i, nm in enumerate(names) if nm.startswith(grp)]].square().mean().sqrt())
                                      for grp in ('regression/random', 'regression/cos', 'independent_random/', 'independent_smooth/', 'independent_local/')}
    gf = torch.Generator(device=DEV).manual_seed(seed + 3)
    zc = torch.randn(g['P3'].shape[1], 16, dtype=torch.float64, device=DEV, generator=gf)
    f = g['data'].quotient(g['wq'][:, None] * (g['P3'] @ zc)); xr = DenseUpperFactor(R).solve(f); xm = fac.solve(f)
    res['physical_force'] = dict(displacement_energy_norm_rms=float(en(xm, xr).square().mean().sqrt()), compliance_relative_max=float(((f * xm).sum(0) / (f * xr).sum(0) - 1).abs().max()))
    del Ahat, fac; torch.cuda.empty_cache()
    res['evaluation_seconds'] = sync() - tick
    return res


def brief(res):
    return dict(seat=res['seat'], held=round(res['held_energy_error'], 4), white=round(res['held_white'], 4), dual=round(res['held_dual'], 4), eA=round(res['schur_relative_error'], 4), chol=res['cholesky_info'],
                smooth_E=round(res['groups']['independent_smooth/']['energy_relative_max'], 4), smooth_inv=round(res['inverse_energy_norm_rms']['independent_smooth/'], 3),
                local_inv=round(res['inverse_energy_norm_rms']['independent_local/'], 3), phys_force=round(res['physical_force']['displacement_energy_norm_rms'], 3),
                compl=round(res['physical_force']['compliance_relative_max'], 3), sec=round(res['evaluation_seconds'], 1))


# ----------------------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--labels', required=True, help='JSON list of records with packet, receipt, reference, trace_cache, seat, split')
    ap.add_argument('--output', required=True); ap.add_argument('--steps', type=int, default=20000); ap.add_argument('--chunk', type=int, default=50)
    ap.add_argument('--eval-every', type=int, default=2000); ap.add_argument('--eval-max-q', type=int, default=23000); ap.add_argument('--eval-labels', type=int, default=3)
    ap.add_argument('--r-near', type=float, default=0.2); ap.add_argument('--decay', type=float, default=0.03); ap.add_argument('--off-scale', type=float, default=OFF_SCALE, help='bound of |L_ij| relative to min(L_ii,L_jj)*exp(-d/decay)')
    ap.add_argument('--rank', type=int, default=512); ap.add_argument('--width', type=int, default=64); ap.add_argument('--hidden', type=int, default=128)
    ap.add_argument('--probes', type=int, default=32); ap.add_argument('--white-probes', type=int, default=32); ap.add_argument('--action-probes', type=int, default=16); ap.add_argument('--action-weight', type=float, default=3.0); ap.add_argument('--dual-weight', type=float, default=1.0); ap.add_argument('--dual-probes', type=int, default=16); ap.add_argument('--dual-start', type=int, default=0); ap.add_argument('--dual-clip', type=float, default=1e4); ap.add_argument('--energy-ramp', type=int, default=3000, help='energy-loss weight ramps linearly from 0 to 1 over this many steps')
    ap.add_argument('--lr', type=float, default=1e-3); ap.add_argument('--warmup', type=int, default=200); ap.add_argument('--lr-floor', type=float, default=0.1)
    ap.add_argument('--seed', type=int, default=2026091209); ap.add_argument('--init-checkpoint', default=None); ap.add_argument('--max-train-labels', type=int, default=1000); ap.add_argument('--train-max-q', type=int, default=24000)
    args = ap.parse_args()
    out = Path(args.output); out.mkdir(parents=True, exist_ok=False); t_start = time.perf_counter(); torch.manual_seed(args.seed)
    write_json(out / 'PROTOCOL.json', dict(vars(args), schema='CUTFEM_SUPERELEMENT_V1', script_sha256=V0.sha256(__file__)))
    records = json.load(open(args.labels))
    train_recs = [r for r in records if r['split'] == 'train' and r['q'] <= args.train_max_q][:args.max_train_labels]; val_recs = [r for r in records if r['split'] != 'train' and r['q'] <= args.train_max_q]
    print(json.dumps(dict(stage='labels', train=[r['seat'] for r in train_recs], validation=[r['seat'] for r in val_recs])), flush=True)
    labels = {int(r['seat']): Label(r, args.r_near, args.decay, args.off_scale) for r in train_recs + val_recs}
    print(json.dumps(dict(stage='prepared', seconds=time.perf_counter() - t_start, q={s: l.q for s, l in labels.items()})), flush=True)
    net = GeometryNet(labels[int(train_recs[0]['seat'])].images.shape[1], args.width, args.rank, args.hidden, off_scale=args.off_scale).to(DEV)
    if args.init_checkpoint: net.load_state_dict(torch.load(args.init_checkpoint, map_location='cuda')['net'])
    nparam = sum(p.numel() for p in net.parameters()); write_json(out / 'MODEL.json', dict(parameters=nparam, model=str(net)))
    print(json.dumps(dict(stage='setup', parameters=nparam)), flush=True)
    opt = torch.optim.Adam(net.parameters(), lr=args.lr)
    gen = torch.Generator(device=DEV).manual_seed(args.seed + 1)
    eval_train = [l for l in labels.values() if l.record['split'] == 'train' and l.q <= args.eval_max_q][:args.eval_labels]
    eval_val = [l for l in labels.values() if l.record['split'] != 'train' and l.q <= args.eval_max_q][:args.eval_labels]
    def run_eval(step):
        rows = []
        for l in eval_train + eval_val:
            g = l.to_gpu(); res = evaluate_label(l, g, net, args.seed); res['step'] = step; res['split'] = l.record['split']; rows.append(res)
            print(json.dumps(dict(stage='evaluation', step=step, split=l.record['split'], **brief(res))), flush=True)
            del g; l.release(); torch.cuda.empty_cache()
        write_json(out / f'EVALUATION_{step:06d}.json', json_finite(rows)); return rows
    evaluations = [run_eval(0)]
    step = 0; order = list(labels[int(r['seat'])] for r in train_recs); rng = np.random.default_rng(args.seed)
    history = []
    while step < args.steps:
        rng.shuffle(order)
        for l in order:
            if step >= args.steps: break
            g = l.to_gpu(); log_w = g['w'].log()
            for _ in range(args.chunk):
                if step >= args.steps: break
                step += 1; tick = sync()
                sched = min(1.0, step / args.warmup) * (args.lr_floor + (1 - args.lr_floor) * 0.5 * (1 + math.cos(math.pi * (step - 1) / max(args.steps - 1, 1))))
                for g_ in opt.param_groups: g_['lr'] = args.lr * sched
                opt.zero_grad(set_to_none=True)
                try:
                    values, M = net(g, log_w); op = Operator(g, values, M)
                    z = draw_probes(g, args.probes, args.white_probes, gen); loss_e = energy_error(g, op, z).mean()
                    zw = torch.randn(g['A'].shape[0], args.action_probes, dtype=torch.float64, device=DEV, generator=gen); loss_a = action_error(g, op, zw).mean()
                    loss_d = torch.log1p(dual_error(g, op, args.dual_probes, gen)).mean() if (args.dual_weight > 0 and step >= args.dual_start) else torch.zeros((), dtype=torch.float64, device=DEV)
                except torch._C._LinAlgError as err:
                    print(json.dumps(dict(stage='guard', step=step, seat=l.seat, reason=repr(err)[:120])), flush=True); continue
                w_e = min(1.0, step / max(args.energy_ramp, 1))
                loss = w_e * loss_e + args.action_weight * loss_a + args.dual_weight * loss_d
                if not torch.isfinite(loss):
                    print(json.dumps(dict(stage='guard', step=step, seat=l.seat)), flush=True); continue
                loss.backward(); gn = torch.nn.utils.clip_grad_norm_(net.parameters(), 10.0)
                if not torch.isfinite(gn):
                    opt.zero_grad(set_to_none=True); print(json.dumps(dict(stage='guard', step=step, seat=l.seat, reason='nonfinite gradient')), flush=True); continue
                opt.step()
                row = dict(step=step, seat=l.seat, lr=args.lr * sched, loss=float(loss.detach()), energy_loss=float(loss_e.detach()), action_loss=float(loss_a.detach()), dual_loss=float(loss_d.detach()), grad_norm=float(gn), seconds=sync() - tick)
                history.append(row); append_json(out / 'HISTORY.jsonl', row)
                if step <= 5 or step % 50 == 0:
                    print(json.dumps(dict(**row, mean_loss_200=float(np.mean([r['loss'] for r in history[-200:]])), elapsed=time.perf_counter() - t_start, peak_gib=torch.cuda.max_memory_allocated() / 2**30)), flush=True)
                if step % args.eval_every == 0 or step == args.steps:
                    torch.save(dict(net=net.state_dict(), step=step), out / f'CHECKPOINT_{step:06d}.pt')
                    del g, op, values, M; l.release(); torch.cuda.empty_cache()
                    evaluations.append(run_eval(step))
                    g = l.to_gpu(); log_w = g['w'].log()
            del g; l.release(); torch.cuda.empty_cache()
    write_json(out / 'RESULT.json', json_finite(dict(status='COMPLETED_FIXED_BUDGET', steps=args.steps, elapsed_seconds=time.perf_counter() - t_start, parameters=nparam,
                                                    peak_gpu_allocated_gib=torch.cuda.max_memory_allocated() / 2**30, initial=evaluations[0], final=evaluations[-1])))
    print(json.dumps(dict(stage='done', elapsed=time.perf_counter() - t_start)), flush=True)


if __name__ == '__main__':
    main()
