"""V1: geometry-conditioned two-scale super-element, trained across FULL labels.

  S_hat(theta) = L_GG^T (I + M M^T)^-1 L_GG
  L_GG : banded factor on the fine face grid, entries generated by a pair head from face-CNN node features
  M    : k dense softening columns generated per DOF by a mode head
Loss: teacher energy metric on physical probes + isotropic action term (same as V0). Labels rotate in chunks.
"""
import argparse, glob, json, math, os, sys, time
import numpy as np, torch
from torch import nn
from torch.nn import functional as F
sys.path.insert(0, '/root/cutfem_neural_a_20260910/source_14301bc56'); sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import v0_superelement as V0
from stage_cutfem_neural_a.data import load_teacher_dense, write_json
from stage_cutfem_neural_a.dense_fit import FactorSample, make_directions, json_finite
from stage_cutfem_neural_a.dense_row_fit import append_json
from stage_cutfem_neural_a.elimination_reference import DenseUpperFactor, load_upper_factor, quotient_dense, evaluate

torch.backends.cuda.matmul.allow_tf32 = False; torch.backends.cudnn.allow_tf32 = False
DEV = torch.device('cuda'); N = 65
S0 = 0.01          # geometry-only stiffness unit (S_ii ~ 0.01 w on 0415)
OFF_SCALE = 10.0   # default bound of |L_ij| relative to min(L_ii, L_jj) times the distance prior; overridden by --off-scale
DEPTHS = (0, 1, 2, 4)


def sync():
    torch.cuda.synchronize(); return time.perf_counter()


# ----------------------------------------------------------------------------- cube symmetries
def cube_group():
    """All 48 signed axis permutations x' = Q (x - c) + c of the unit cube; identity first."""
    import itertools
    elems = []
    for perm in itertools.permutations(range(3)):
        for sign in itertools.product((1, -1), repeat=3):
            elems.append((perm, sign))
    elems.sort(key=lambda e: (e != ((0, 1, 2), (1, 1, 1))))
    return elems


def transform_grid(grid, perm, sign, N):
    """grid: (11, N, N, N) analytic field. Returns the field of the transformed geometry (vector channels rotated)."""
    Q = np.zeros((3, 3)); 
    for a in range(3): Q[a, perm[a]] = sign[a]
    idx = np.stack(np.meshgrid(*[np.arange(N)] * 3, indexing='ij'), axis=-1) - (N - 1) / 2      # target indices centered
    src = (idx @ Q) + (N - 1) / 2                                                                  # source = Q^-1 target = Q^T target
    src = np.rint(src).astype(int)
    out = grid[:, src[..., 0], src[..., 1], src[..., 2]]
    out[0:3] = np.einsum('ab,bxyz->axyz', Q, out[0:3] - 0.5) + 0.5
    out[7:10] = np.einsum('ab,bxyz->axyz', Q, out[7:10])
    return out, Q


def transform_theta(theta, perm, sign):
    """tau corners permuted with the cube corners, cut plane a.x <= b mapped through x' = Q(x-c)+c."""
    import itertools
    Q = np.zeros((3, 3)); 
    for a in range(3): Q[a, perm[a]] = sign[a]
    corners = np.array(list(itertools.product((0, 1), repeat=3)), dtype=float)
    moved = (corners - 0.5) @ Q.T + 0.5
    order = [int(np.argmin(np.abs(corners - m).sum(1))) for m in moved]          # corner k moves to corners[order[k]]
    tau = np.zeros(8); tau[order] = theta[:8]
    a, b = theta[8:11], theta[11]; c = np.full(3, 0.5)
    a2 = Q @ a; b2 = b - a @ c + a2 @ c
    return np.concatenate((tau, a2, [b2]))


def build_images(grid, ijk, w, N):
    """Six face images from an analytic field: channels at several depths, node mask, support weight, coordinates, face one-hot."""
    mem = []
    for f in range(6):
        ax, side = f // 2, f % 2; on = np.nonzero(ijk[:, ax] == (0 if side == 0 else N - 1))[0]
        free = [a for a in range(3) if a != ax]
        for i in on: mem.append((i, f, ijk[i, free[0]], ijk[i, free[1]]))
    mem = np.array(mem); imgs = []
    for f in range(6):
        ax, side = f // 2, f % 2
        ch = [np.take(grid, dep if side == 0 else N - 1 - dep, axis=1 + ax) for dep in DEPTHS]
        mask = np.zeros((N, N)); wimg = np.zeros((N, N)); sel = mem[mem[:, 1] == f]
        mask[sel[:, 2], sel[:, 3]] = 1.0; wimg[sel[:, 2], sel[:, 3]] = w[sel[:, 0]]
        uu, vv = np.meshgrid(np.linspace(0, 1, N), np.linspace(0, 1, N), indexing='ij')
        onehot = np.zeros((6, N, N)); onehot[f] = 1.0
        imgs.append(np.concatenate(ch + [mask[None], wimg[None], uu[None], vv[None], onehot], axis=0))
    return np.stack(imgs).astype(np.float32), mem


# ----------------------------------------------------------------------------- label container
class Label:
    def __init__(self, record, r_near, decay, off_scale, coarse_stride=4):
        self.record = record; self.seat = int(record['seat'])
        self.sample = FactorSample(record, 2026091197); self.data = self.sample.data; cache = self.sample.cache
        assert np.all(np.diff(cache['indptr']) == 1) and np.allclose(cache['coefficients'], 1.0), 'nodal trace functionals required'
        self.ijk = np.stack(np.unravel_index(cache['background_nodes'][cache['indices']], (N, N, N)), axis=1)
        self.nn = len(self.ijk); self.q = 3 * self.nn; self.d = self.data.dimension
        assert self.d == self.q - 6
        self.w = np.clip(V0.support_weights(self.ijk, N, cache['tau_corners'], cache['cut_plane']), 1e-4, 1.0)
        self.wq = torch.from_numpy(self.w).double().repeat_interleave(3)
        self.P3 = torch.from_numpy(np.kron(V0.coarse_interpolation(self.ijk, N, coarse_stride), np.eye(3)))
        self.theta = torch.from_numpy(np.concatenate((cache['tau_corners'], cache['cut_plane']))).float()
        self.grid_np = self.data.grid[0].numpy().copy()                        # (11, 65, 65, 65)
        imgs, mem = build_images(self.grid_np, self.ijk, self.w, N)
        self.images = torch.from_numpy(imgs); self.mem_node = torch.from_numpy(mem[:, 0]); self.mem_face = torch.from_numpy(mem[:, 1])
        self.mem_pix = torch.from_numpy(mem[:, 2] * N + mem[:, 3]); self.face_of_node = torch.from_numpy(V0.face_ids(self.ijk, N))
        self.volume = torch.from_numpy(self.grid_np[:, ::2, ::2, ::2].copy())    # (11, 33, 33, 33) coarse volume field
        self._aug_cache = {}
        # near-field node pairs and the sorted DOF band
        xyz = torch.from_numpy(self.ijk / (N - 1)).to(DEV).double()
        ni, nj = V0.pairs_within(xyz, xyz, r_near, upper=True)
        off = ni != nj; pi, pj = ni[off], nj[off]
        self.pair_i, self.pair_j = pi.cpu(), pj.cpu()
        dvec = (xyz[pj] - xyz[pi]); self.pair_dx = dvec.float().cpu(); dist = torch.linalg.vector_norm(dvec, dim=1)
        self.xyz_nodes = torch.from_numpy(self.ijk / (N - 1)).float()
        self.pair_decay = torch.exp(-dist / decay).cpu()
        # DOF entries: off-diagonal blocks (9 per pair) and diagonal blocks (6 per node)
        a = torch.arange(3); npair = len(pi)
        I_off = (pi[:, None, None] * 3 + a[None, :, None].to(DEV)).expand(-1, 3, 3).reshape(-1)
        J_off = (pj[:, None, None] * 3 + a[None, None, :].to(DEV)).expand(-1, 3, 3).reshape(-1)
        node = torch.arange(self.nn, device=DEV); ua, ub = torch.triu_indices(3, 3)
        I_dg = (node[:, None] * 3 + ua[None, :].to(DEV)).reshape(-1); J_dg = (node[:, None] * 3 + ub[None, :].to(DEV)).reshape(-1)
        I = torch.cat((I_off, I_dg)); J = torch.cat((J_off, J_dg))
        order = torch.argsort(I * self.q + J)
        self.band_index = torch.stack((I[order], J[order])).cpu(); self.band_index_t = torch.stack((J[order], I[order])).cpu()
        self.band_perm = order.cpu()                                       # position in [off entries (npair*9) | diag entries (nn*6)]
        crow = torch.zeros(self.q + 1, dtype=torch.int64); crow[1:] = torch.bincount(I[order].cpu(), minlength=self.q).cumsum(0); self.band_crow = crow
        self.n_off_entries = npair * 9
        self.band_is_diag = (self.band_index[0] == self.band_index[1])
        self.dirs = None                                                   # evaluation directions, built lazily on GPU
        self.ext_max = self.ext_min = None                                 # warm-started blocks of the extreme whitened modes

    def coarse_basis(self, stride=4, prune=0.05):
        """Orthonormal basis (q x k) of the coarse face space: Q2 interpolation from the stride grid, coarse nodes with negligible
        material overlap pruned, rigid modes projected out. Cached on the CPU."""
        key = (stride, prune)
        if getattr(self, '_coarse', None) is None or self._coarse[0] != key:
            P = torch.from_numpy(np.kron(V0.coarse_interpolation(self.ijk, N, stride), np.eye(3)))
            colnorm = P.abs().sum(0); P = P[:, colnorm >= prune * colnorm.max()]
            Nr = torch.from_numpy(self.sample.cache['rigid']).double(); P = P - Nr @ torch.linalg.solve(Nr.T @ Nr, Nr.T @ P)
            Q, Rf = torch.linalg.qr(P); keep = Rf.diagonal().abs() > 1e-8 * Rf.diagonal().abs().max()
            self._coarse = (key, Q[:, keep].contiguous())
        return self._coarse[1]

    def to_gpu(self, need_A=True, need_Z=False, z_dtype=torch.float32):
        """need_A: dense teacher quotient A (probe losses, legacy evaluation). need_Z: Z^T = B^T R*^-1 (q x d) for the exact trace term."""
        g = dict(images=self.images.to(DEV), theta=self.theta.to(DEV), mem_node=self.mem_node.to(DEV), mem_face=self.mem_face.to(DEV), mem_pix=self.mem_pix.to(DEV),
                 volume=self.volume.to(DEV), xyz=self.xyz_nodes.to(DEV), Q=torch.eye(3, dtype=torch.float64, device=DEV),
                 face_of_node=self.face_of_node.to(DEV), pair_i=self.pair_i.to(DEV), pair_j=self.pair_j.to(DEV), pair_dx=self.pair_dx.to(DEV), pair_decay=self.pair_decay.to(DEV),
                 band_index=self.band_index.to(DEV), band_index_t=self.band_index_t.to(DEV), band_perm=self.band_perm.to(DEV), band_crow=self.band_crow.to(DEV), wq=self.wq.to(DEV), P3=self.P3.to(DEV),
                 w=torch.from_numpy(self.w).double().to(DEV), band_is_diag=self.band_is_diag.to(DEV), d=self.d)
        data = self.data.cuda() if DEV.type == 'cuda' else self.data.cpu()
        A = None
        if need_A:
            S, _ = load_teacher_dense(self.record['packet'], data.quotient.dimension, DEV)
            A, _ = quotient_dense(S, data.quotient); del S
        Rstar = load_upper_factor(Path(self.record['reference']) / 'R_UPPER.npy', self.d, DEV)
        rigid = torch.from_numpy(self.sample.cache['rigid']).to(DEV).double()
        g.update(data=data, A=A, Rstar=Rstar, rigid=rigid, tri_mode=getattr(self, 'tri_mode', 'dense'),
                 logdet_A=2.0 * float(Rstar.diagonal().log().sum()), logdet_NtN=float(torch.logdet(rigid.T @ rigid)))
        if need_Z:
            B = data.quotient(torch.eye(self.q, dtype=torch.float64, device=DEV))                       # (d, q), orthonormal rows
            Z = torch.linalg.solve_triangular(Rstar.T, B, upper=False); del B                            # Z = R*^-T B
            g['ZT'] = Z.T.contiguous().to(z_dtype); del Z
        if getattr(self, '_coarse', None) is not None: g['Pq'] = self._coarse[1].to(DEV)
        if self.ext_max is not None: g['ext'] = (self.ext_max.to(DEV), self.ext_min.to(DEV))
        return g

    def store_extremes(self, g):
        if 'ext' in g: self.ext_max, self.ext_min = g['ext'][0].cpu(), g['ext'][1].cpu()

    def transformed(self, perm, sign):
        """Geometry inputs of the symmetry-transformed label (node order unchanged); Q maps original to transformed components."""
        key = (tuple(perm), tuple(sign))
        if key not in self._aug_cache:
            grid2, Q = transform_grid(self.grid_np, perm, sign, N)
            ijk2 = np.rint((self.ijk - (N - 1) / 2) @ Q.T + (N - 1) / 2).astype(int)
            imgs, mem = build_images(grid2, ijk2, self.w, N)
            self._aug_cache[key] = dict(images=torch.from_numpy(imgs), mem_node=torch.from_numpy(mem[:, 0]), mem_face=torch.from_numpy(mem[:, 1]),
                mem_pix=torch.from_numpy(mem[:, 2] * N + mem[:, 3]), face_of_node=torch.from_numpy(V0.face_ids(ijk2, N)),
                pair_dx=(self.pair_dx.double() @ torch.from_numpy(Q).T).float(), theta=torch.from_numpy(transform_theta(self.theta.numpy(), perm, sign)).float(),
                volume=torch.from_numpy(grid2[:, ::2, ::2, ::2].copy()), xyz=torch.from_numpy(ijk2 / (N - 1)).float(), Q=torch.from_numpy(Q))
        return {k: v.to(DEV) for k, v in self._aug_cache[key].items()}

    def release(self):
        self.data = self.data.cpu(); torch.cuda.empty_cache()


from pathlib import Path


# ----------------------------------------------------------------------------- network
class ResBlock(nn.Module):
    def __init__(self, c, dilation):
        super().__init__()
        self.c1 = nn.Conv2d(c, c, 3, padding=dilation, dilation=dilation); self.c2 = nn.Conv2d(c, c, 3, padding=1)
        self.norm = nn.GroupNorm(8, c)
    def forward(self, x):
        return x + self.c2(F.silu(self.c1(F.silu(self.norm(x)))))


class VolumeNet(nn.Module):
    """Coarse 3D branch on the 33^3 analytic field; features sampled at the face nodes feed the mode head."""
    def __init__(self, c_in=11, width=32):
        super().__init__()
        self.net = nn.Sequential(nn.Conv3d(c_in, 16, 3, padding=1), nn.SiLU(), nn.Conv3d(16, width, 3, stride=2, padding=1), nn.SiLU(),
                                 nn.Conv3d(width, width, 3, padding=1), nn.SiLU(), nn.Conv3d(width, width, 3, padding=1))
        self.width = width
    def forward(self, volume, xyz):
        f = self.net(volume[None])                                            # (1, C, 17, 17, 17)
        pts = (2 * xyz[:, [2, 1, 0]] - 1)[None, :, None, None]                # grid_sample takes z,y,x order
        return F.grid_sample(f, pts, mode='bilinear', align_corners=True, padding_mode='border')[0, :, :, 0, 0].T    # (n, C)


class GeometryNet(nn.Module):
    def __init__(self, c_in, width=64, rank=512, hidden=128, dilations=(1, 2, 4, 8), off_scale=OFF_SCALE, volume_width=32):
        super().__init__()
        self.width, self.rank, self.off_scale = width, rank, off_scale
        self.volume = VolumeNet(11, volume_width) if volume_width else None
        self.vol_norm = nn.LayerNorm(volume_width) if volume_width else None
        self.stem = nn.Conv2d(c_in, width, 3, padding=1)
        self.blocks = nn.ModuleList([ResBlock(width, dl) for dl in dilations])
        self.context = nn.Sequential(nn.Linear(width + 12, width), nn.SiLU(), nn.Linear(width, width))
        self.node_norm = nn.LayerNorm(width)
        self.diag = nn.Sequential(nn.Linear(width, hidden), nn.SiLU(), nn.Linear(hidden, 6))          # 3 log-diag corrections + 3 in-block off values
        self.pair = nn.Sequential(nn.Linear(2 * width + 4 + 12, hidden), nn.SiLU(), nn.Linear(hidden, hidden), nn.SiLU(), nn.Linear(hidden, 9))
        self.mode = nn.Sequential(nn.Linear(width + (volume_width or 0), hidden), nn.SiLU(), nn.Linear(hidden, 3 * rank))
        self.mode_logscale = nn.Parameter(torch.full((rank,), math.log(0.03)))
        for head in (self.diag, self.pair, self.mode):
            nn.init.normal_(head[-1].weight, std=1e-2); nn.init.zeros_(head[-1].bias)

    def node_features(self, g):
        x = self.stem(g['images'])
        for b in self.blocks: x = b(x)
        ctx = self.context(torch.cat((x.mean(dim=(0, 2, 3)), g['theta'])))
        flat = x.flatten(2)                                                  # (6, C, 65*65)
        feats = flat[g['mem_face'], :, g['mem_pix']]                         # (memberships, C)
        n = int(g['face_of_node'].shape[0])
        h = torch.zeros((n, self.width), device=DEV, dtype=feats.dtype).index_add_(0, g['mem_node'], feats)
        cnt = torch.zeros(n, device=DEV, dtype=feats.dtype).index_add_(0, g['mem_node'], torch.ones_like(feats[:, 0]))
        return self.node_norm(h / cnt[:, None] + ctx[None, :])

    def preactivations(self, g):
        """Head outputs before the bounded maps: dg (n, 6), pair (npair, 9), mode (n, 3 rank)."""
        h = self.node_features(g)
        fi = F.one_hot(g['face_of_node'], 6).float(); pi, pj = g['pair_i'], g['pair_j']
        inp = torch.cat((h[pi], h[pj], 5.0 * g['pair_dx'], (g['face_of_node'][pi] == g['face_of_node'][pj]).float()[:, None], fi[pi], fi[pj]), dim=1)
        hm = torch.cat((h, self.vol_norm(self.volume(g['volume'], g['xyz']))), dim=1) if self.volume is not None else h
        return self.diag(h), self.pair(inp), self.mode(hm)

    def forward(self, g, log_w):
        """Returns band COO values (sorted order, float64) and M (q x rank, float64).
        Off-diagonal band entries are bounded by the smaller of the two diagonals they connect, times a distance prior,
        so every row of L stays within a bounded ratio of its diagonal and the triangular solves stay stable."""
        dg, pair, mode = self.preactivations(g)
        return bounded_values(dg.double(), pair.double(), mode.double(), self.mode_logscale.double(), g, log_w, self.rank, self.off_scale)


def bounded_values(dg, pair, mode, mode_logscale, g, log_w, rank, off_scale):
    """The bounded maps shared by the geometry network and the free-coefficient model (all float64):
    diag = sqrt(S0 w) exp(3 tanh(dg/3)); in-block and pair entries = tanh(.) min(D_i, D_j) off_scale [exp(-d/decay)]; M = 0.1 tanh(.) exp(logscale)."""
    values = bounded_band(dg, pair, g, log_w, off_scale)
    M = (0.1 * torch.tanh(mode)).view(-1, rank) * mode_logscale.exp()[None, :]
    return values, M


def bounded_band(dg, pair, g, log_w, off_scale):
    n = dg.shape[0]
    logdiag = math.log(S0) * 0.5 + 0.5 * log_w[:, None] + 3.0 * torch.tanh(dg[:, :3] / 3.0); D = logdiag.exp()
    ua, ub = torch.triu_indices(3, 3, device=DEV); is_d = ua == ub
    dvals = torch.empty((n, 6), dtype=torch.float64, device=DEV)
    dvals[:, is_d] = D; dvals[:, ~is_d] = off_scale * torch.minimum(D[:, ua[~is_d]], D[:, ub[~is_d]]) * torch.tanh(dg[:, 3:])
    pi, pj = g['pair_i'], g['pair_j']; dmin = torch.minimum(D[pi][:, :, None], D[pj][:, None, :]).reshape(-1, 9)
    blocks = torch.tanh(pair) * dmin * (off_scale * g['pair_decay'])[:, None]
    return torch.cat((blocks.reshape(-1), dvals.reshape(-1)))[g['band_perm']]


class FreeCoefficientModel(nn.Module):
    """Free coefficients through exactly the same bounded maps as the GeometryNet heads (pre-activations become parameters).
    Single label, no symmetry frames: a capacity test of the representation under the network's feasible set."""
    def __init__(self, label, rank=512, off_scale=OFF_SCALE):
        super().__init__(); self.rank, self.off_scale = rank, off_scale
        self.dg = nn.Parameter(torch.zeros(label.nn, 6, dtype=torch.float64)); self.pair_p = nn.Parameter(torch.zeros(len(label.pair_i), 9, dtype=torch.float64))
        self.mode_p = nn.Parameter(1e-2 * torch.randn(label.nn, 3 * rank, dtype=torch.float64)); self.mode_logscale = nn.Parameter(torch.full((rank,), math.log(0.03), dtype=torch.float64))
    @torch.no_grad()
    def from_network(self, net, g):
        dg, pair, mode = net.preactivations(g)
        self.dg.copy_(dg.double()); self.pair_p.copy_(pair.double()); self.mode_p.copy_(mode.double()); self.mode_logscale.copy_(net.mode_logscale.double())
        return self
    def forward(self, g, log_w):
        return bounded_values(self.dg, self.pair_p, self.mode_p, self.mode_logscale, g, log_w, self.rank, self.off_scale)


class FreeUnboundedModel(nn.Module):
    """Free band coefficients (network head bounds) plus a free, unbounded M (q x rank): the representation class itself, no head bound on M."""
    def __init__(self, label, rank=1024, off_scale=OFF_SCALE):
        super().__init__(); self.rank, self.off_scale = rank, off_scale
        self.dg = nn.Parameter(torch.zeros(label.nn, 6, dtype=torch.float64)); self.pair_p = nn.Parameter(torch.zeros(len(label.pair_i), 9, dtype=torch.float64))
        self.M = nn.Parameter(1e-3 * torch.randn(label.q, rank, dtype=torch.float64))
    @torch.no_grad()
    def from_network(self, net, g):
        dg, pair, mode = net.preactivations(g); self.dg.copy_(dg.double()); self.pair_p.copy_(pair.double())
        Mn = (0.1 * torch.tanh(mode.double())).view(-1, net.rank) * net.mode_logscale.exp().double()[None, :]; k = min(net.rank, self.rank)
        self.M[:, :k].copy_(Mn[:, :k]); self.M[:, k:].mul_(float(Mn.abs().mean())); return self
    def forward(self, g, log_w):
        return bounded_band(self.dg, self.pair_p, g, log_w, self.off_scale), self.M


class FreeCoarseModel(nn.Module):
    """Free band coefficients (same bounded maps as the network heads) plus a coarse-space compliance:
    K0^-1 = L^-1 L^-T + Pq G Pq^T with G = C C^T, C lower triangular with positive diagonal (free k x k) on the orthonormal
    coarse basis Pq; M = L Pq C. Cholesky-type parameterization: unique, positive definite, no eigen-decomposition in the graph."""
    def __init__(self, label, off_scale=OFF_SCALE, k=None):
        super().__init__(); self.off_scale = off_scale; self.k = k
        self.dg = nn.Parameter(torch.zeros(label.nn, 6, dtype=torch.float64)); self.pair_p = nn.Parameter(torch.zeros(len(label.pair_i), 9, dtype=torch.float64))
        self.C_raw = nn.Parameter(torch.zeros(k, k, dtype=torch.float64))
    @torch.no_grad()
    def from_network(self, net, g):
        dg, pair, _ = net.preactivations(g); self.dg.copy_(dg.double()); self.pair_p.copy_(pair.double()); return self
    def C(self):
        return torch.tril(self.C_raw, -1) + torch.diag(self.C_raw.diagonal().exp())
    def logdet_G(self): return 2.0 * float(self.C_raw.diagonal().sum())
    def forward(self, g, log_w):
        values = bounded_band(self.dg, self.pair_p, g, log_w, self.off_scale)
        q = g['Pq'].shape[0]; L = torch.sparse_coo_tensor(g['band_index'], values, (q, q), is_coalesced=True)
        return values, torch.sparse.mm(L, g['Pq'] @ self.C())
    @torch.no_grad()
    def init_coarse_from_teacher(self, g, values, floor=1e-4):
        """G = Pq^T (A^-1 - L^-1 L^-T) Pq on the quotient, eigenvalues floored at floor x the teacher's coarse compliance scale."""
        Pq = g['Pq']; q = Pq.shape[0]
        Zc = torch.linalg.solve_triangular(g['Rstar'].T, g['data'].quotient(Pq), upper=False); Gt = Zc.T @ Zc; del Zc            # coarse teacher compliance
        Ld = torch.sparse_coo_tensor(g['band_index'], values, (q, q), is_coalesced=True).to_dense()
        X = torch.linalg.solve_triangular(Ld.T, Pq, upper=False); del Ld; Gl = X.T @ X; del X                                   # coarse local compliance
        lam, U = torch.linalg.eigh(Gt - Gl); scale = float(torch.linalg.eigvalsh(Gt).max()); floored = int((lam < floor * scale).sum()); lam = lam.clamp(min=floor * scale)
        Cc = torch.linalg.cholesky((U * lam[None, :]) @ U.T)
        self.C_raw.copy_(torch.tril(Cc, -1) + torch.diag(Cc.diagonal().log()))
        return dict(coarse_teacher_compliance_max=scale, coarse_local_compliance_max=float(torch.linalg.eigvalsh(Gl).max()), floored=floored)


class BandTriSolve(torch.autograd.Function):
    """Solve L X = B (upper=True) or L^T X = B (upper=False) for the banded upper-triangular L given by COO (index, values).
    mode='dense': cuBLAS trsm on a dense copy of L (fast, q^2 memory, rebuilt in backward).
    mode='sparse': cuSPARSE CSR triangular solve (no q^2 memory, slower on long dependency chains).
    Backward computes the gradient only on the band."""
    @staticmethod
    def solve(values, B, index, crow, q, upper, mode):
        if mode == 'sparse':
            csr = torch.sparse_csr_tensor(crow, index[1], values, (q, q))
            return torch.triangular_solve(B, csr, upper=True, transpose=not upper)[0]
        L = torch.sparse_coo_tensor(index, values, (q, q), is_coalesced=True).to_dense()
        return torch.linalg.solve_triangular(L if upper else L.T, B, upper=upper)
    @staticmethod
    def forward(ctx, values, B, index, crow, q, upper, mode):
        X = BandTriSolve.solve(values.detach(), B, index, crow, q, upper, mode)
        ctx.save_for_backward(values.detach(), X, index, crow); ctx.q, ctx.upper, ctx.mode = q, upper, mode
        return X
    @staticmethod
    def backward(ctx, dX):
        values, X, index, crow = ctx.saved_tensors; q, upper, mode = ctx.q, ctx.upper, ctx.mode
        # X = L^-1 B:  dB = L^-T dX,  dL[i,j] = -(L^-T dX)_i . X_j ;   X = L^-T B:  dB = L^-1 dX,  dL[i,j] = -X_i . (L^-1 dX)_j
        Y = BandTriSolve.solve(values, dX, index, crow, q, not upper, mode)
        I, J = index[0], index[1]; g = torch.empty(I.shape[0], dtype=values.dtype, device=values.device)
        for b in range(0, I.shape[0], 2_000_000):
            i, j = I[b:b + 2_000_000], J[b:b + 2_000_000]
            g[b:b + 2_000_000] = -((Y[i] * X[j]).sum(1) if upper else (X[i] * Y[j]).sum(1))
        return g, Y, None, None, None, None, None


class Operator:
    """S_hat = L^T (I + M M^T)^-1 L, applied by Woodbury with G = I + M^T M."""
    def __init__(self, g, values, M):
        self.q = int(M.shape[0]); self.values = values; self.index = g['band_index']; self.crow = g['band_crow']; self.tri_mode = g.get('tri_mode', 'dense')
        Q = g.get('Q'); self.Q = None if Q is None or bool(torch.equal(Q, torch.eye(3, dtype=Q.dtype, device=Q.device))) else Q
        self.L = torch.sparse_coo_tensor(g['band_index'], values, (self.q, self.q), is_coalesced=True)
        self.LT = torch.sparse_coo_tensor(g['band_index_t'], values, (self.q, self.q)); self.M = M
        G = M.T @ M; G.diagonal().add_(1.0); self.C = torch.linalg.cholesky(G)
    def pi(self, x, inverse=False):
        """Apply Pi = I (x) Q (or its transpose) to node-major vectors: original frame <-> transformed frame."""
        if self.Q is None: return x
        X = x.reshape(-1, 3, x.shape[1]); Qm = (self.Q.T if inverse else self.Q).to(x.dtype)
        return torch.einsum('ab,nbm->nam', Qm, X).reshape(x.shape)
    def apply(self, x):
        x = self.pi(x)
        u = torch.sparse.mm(self.L, x); t = self.M.T @ u
        u = u - self.M @ torch.cholesky_solve(t, self.C)
        return self.pi(torch.sparse.mm(self.LT, u), inverse=True)
    def restricted_inverse(self, quotient, rigid, y):
        """x_hat = (B S_hat B^T)^-1 y via full-space solves S_hat^-1 = L^-1 (I + M M^T) L^-T and a rank-6 rigid correction."""
        Fm = self.pi(torch.cat((quotient.lift(y), rigid), dim=1))
        Z = BandTriSolve.apply(self.values, Fm, self.index, self.crow, self.q, False, self.tri_mode); Z = Z + self.M @ (self.M.T @ Z)
        U = self.pi(BandTriSolve.apply(self.values, Z, self.index, self.crow, self.q, True, self.tri_mode), inverse=True); m = y.shape[1]; UF, UN = U[:, :m], U[:, m:]
        return quotient(UF - UN @ torch.linalg.solve(rigid.T @ UN, rigid.T @ UF))
    def solve_full(self, Y):
        """S_hat^-1 Y on the full face space (no rigid correction), in the original frame."""
        Z = BandTriSolve.apply(self.values, self.pi(Y), self.index, self.crow, self.q, False, self.tri_mode); Z = Z + self.M @ (self.M.T @ Z)
        return self.pi(BandTriSolve.apply(self.values, Z, self.index, self.crow, self.q, True, self.tri_mode), inverse=True)
    @torch.no_grad()
    def materialize(self):
        Y = torch.linalg.solve_triangular(self.C, self.M.T, upper=False)
        T = -(Y.T @ Y); del Y; T.diagonal().add_(1.0)
        Q1 = torch.sparse.mm(self.LT, T); del T
        S = torch.sparse.mm(self.LT, Q1.T.contiguous()); del Q1
        S = 0.5 * (S + S.T)
        if self.Q is not None:                                                # back to the original frame: Pi^T S' Pi
            S = self.pi(self.pi(S, inverse=True).T, inverse=True).T
        return S


# ----------------------------------------------------------------------------- probes, loss, evaluation
def draw_probes(g, m, white, generator):
    q, d = g['P3'].shape[0], g['A'].shape[0]; mc = m // 2
    zc = torch.randn(g['P3'].shape[1], mc, dtype=torch.float64, device=DEV, generator=generator)
    xf = torch.randn(q, m - mc, dtype=torch.float64, device=DEV, generator=generator) * g['wq'].sqrt()[:, None]
    z = g['data'].quotient(torch.cat((g['P3'] @ zc, xf), dim=1))
    if white:
        xi = torch.randn(d, white, dtype=torch.float64, device=DEV, generator=generator)
        z = torch.cat((z, torch.linalg.solve_triangular(g['Rstar'], xi, upper=True)), dim=1)
    return z


def energy_error(g, op, z):
    ref = g['A'] @ z; pred = g['data'].quotient(op.apply(g['data'].quotient.lift(z)))
    return torch.linalg.solve_triangular(g['Rstar'].T, pred - ref, upper=False).square().sum(0) / (g['Rstar'] @ z).square().sum(0)


def dual_error(g, op, m, generator, kind='white'):
    """Inverse (response) error. kind='white': forces uniform over modes in the energy metric.
    kind='physical': support-weighted smooth tractions (half) and support-weighted random balanced loads (half).
    Returns (energy-norm relative displacement error, relative compliance error) per probe."""
    R = g['Rstar']; d = g['A'].shape[0]
    if kind == 'white':
        xi = torch.randn(d, m, dtype=torch.float64, device=DEV, generator=generator); y = R.T @ xi
        xr = torch.linalg.solve_triangular(R, xi, upper=True)
    else:
        q = g['P3'].shape[0]; mc = m // 2
        zc = torch.randn(g['P3'].shape[1], mc, dtype=torch.float64, device=DEV, generator=generator)
        xf = torch.randn(q, m - mc, dtype=torch.float64, device=DEV, generator=generator)
        y = g['data'].quotient(g['wq'][:, None] * torch.cat((g['P3'] @ zc, xf), dim=1))
        xr = torch.linalg.solve_triangular(R, torch.linalg.solve_triangular(R.T, y, upper=False), upper=True)
    xh = op.restricted_inverse(g['data'].quotient, g['rigid'], y)
    e_disp = (R @ (xh - xr)).square().sum(0) / (R @ xr).square().sum(0)
    e_comp = ((y * xh).sum(0) - (y * xr).sum(0)).abs() / (y * xr).sum(0).abs()
    return e_disp, e_comp


# ----------------------------------------------------------------------------- probe-free objective: log-det divergence + extreme whitened modes
def divergence_terms(g, op, trace_dtype=torch.float32, solve_tol=1e-6):
    """Exact log-det divergence of the student against the teacher, D = tr(A^-1 A_hat) - log det(A^-1 A_hat) - d = sum_i (mu_i - log mu_i - 1)
    over the whitened spectrum mu of R*^-T A_hat R*^-1.  No probes:
      tr(A^-1 A_hat) = ||(I + M M^T)^-1/2 L Pi Z^T||_F^2 with Z = R*^-T B (Pi: augmentation frame),
      log det A_hat  = 2 sum log L_ii - log det(I + M^T M) + log det(N^T S_hat^-1 N) - log det(N^T N)   (orthonormal rigid quotient B).
    The trace is evaluated in trace_dtype (float32 is enough for its gradient); the value logged is exact up to that rounding.
    Returns (D, trace, log-det gap, solve residual). When the rigid-correction solve residual exceeds solve_tol the step is numerically
    unreliable: the rigid term is dropped (gap then lacks a per-label constant) so that no gradient flows through the ill-conditioned solve."""
    ZT = op.pi(g['ZT']).to(trace_dtype)
    L = torch.sparse_coo_tensor(op.index, op.values.to(trace_dtype), (op.q, op.q), is_coalesced=True)
    T = torch.sparse.mm(L, ZT)                                                                          # (q, d)
    Y = torch.linalg.solve_triangular(op.C.to(trace_dtype), op.M.to(trace_dtype).T @ T, upper=False)   # C^-1 M^T T
    trace = (T.square().sum() - Y.square().sum()).double(); del T, Y
    logdet_S = 2.0 * op.values[g['band_is_diag']].log().sum() - 2.0 * op.C.diagonal().log().sum()
    N = g['rigid']; U = op.solve_full(N)
    with torch.no_grad(): residual = float(torch.linalg.matrix_norm(op.apply(U) - N) / torch.linalg.matrix_norm(N))   # K0 U = N solve residual
    if residual > solve_tol:                                                                             # ill-conditioned K0: keep only the solve-free part
        return trace - (logdet_S - g['logdet_A']) - g['d'], trace, logdet_S - g['logdet_A'], residual
    logdet_hat = logdet_S + torch.logdet(N.T @ U) - g['logdet_NtN']
    gap = logdet_hat - g['logdet_A']
    return trace - gap - g['d'], trace, gap, residual


@torch.no_grad()
def factor_conditioning(op, iters=30):
    """Estimates of sigma_max(L), sigma_min(L) (power / inverse iteration on L^T L) and ||M||_2; K0 is bounded by
    sigma_min(L)^2 / (1 + ||M||^2) <= K0 <= sigma_max(L)^2."""
    q = op.q; v = torch.randn(q, 1, dtype=torch.float64, device=DEV); v /= v.norm()
    for _ in range(iters):
        v = torch.sparse.mm(op.LT, torch.sparse.mm(op.L, v)); smax = v.norm().sqrt(); v /= v.norm()
    v = torch.randn(q, 1, dtype=torch.float64, device=DEV); v /= v.norm()
    Ld = torch.sparse_coo_tensor(op.index, op.values, (q, q), is_coalesced=True).to_dense()
    for _ in range(iters):
        v = torch.linalg.solve_triangular(Ld, torch.linalg.solve_triangular(Ld.T, v, upper=False), upper=True); smin = 1.0 / v.norm().sqrt(); v /= v.norm()
    del Ld
    mnorm = torch.linalg.eigvalsh(op.M.T @ op.M).max().sqrt()
    return dict(L_sigma_max=float(smax), L_sigma_min=float(smin), M_norm=float(mnorm), K0_condition_bound=float(smax ** 2 * (1 + mnorm ** 2) / smin ** 2))


def whiten_apply(g, op, V):
    """W V with W = R*^-T (B S_hat B^T) R*^-1 (differentiable through the student)."""
    X = torch.linalg.solve_triangular(g['Rstar'], V, upper=True)
    Y = g['data'].quotient(op.apply(g['data'].quotient.lift(X)))
    return torch.linalg.solve_triangular(g['Rstar'].T, Y, upper=False)


def whiten_solve(g, op, V):
    """W^-1 V = R* (B S_hat B^T)^-1 R*^T V."""
    return g['Rstar'] @ op.restricted_inverse(g['data'].quotient, g['rigid'], g['Rstar'].T @ V)


def extreme_terms(g, op, iters, block, generator=None):
    """Block power iteration (warm-started in g['ext']) towards the stiffest and softest whitened modes of the student relative to the teacher;
    returns the divergence density of the Ritz values, mean(phi(ritz)) with phi(mu) = mu - log mu - 1, and the Ritz values themselves."""
    d = g['Rstar'].shape[0]
    if 'ext' not in g:
        V0_ = torch.randn(d, 2 * block, dtype=torch.float64, device=DEV, generator=generator)
        g['ext'] = (torch.linalg.qr(V0_[:, :block])[0], torch.linalg.qr(V0_[:, block:])[0])
    Vmax, Vmin = g['ext']
    with torch.no_grad():
        for _ in range(iters):
            Vmax = torch.linalg.qr(whiten_apply(g, op, Vmax))[0]; Vmin = torch.linalg.qr(whiten_solve(g, op, Vmin))[0]
    g['ext'] = (Vmax, Vmin)
    ritz = []
    for V in (Vmax, Vmin):
        H = V.T @ whiten_apply(g, op, V); ritz.append(torch.linalg.eigvalsh(0.5 * (H + H.T)))
    ritz = torch.cat(ritz)
    return (ritz - ritz.log() - 1.0).mean(), ritz


def action_error(g, op, z):
    ref = g['A'] @ z; pred = g['data'].quotient(op.apply(g['data'].quotient.lift(z)))
    return (pred - ref).square().sum(0) / ref.square().sum(0)


@torch.no_grad()
def evaluate_spectral(label, g, net, seed):
    """Probe-free metrics: exact divergence per mode (float32 trace), log-det gap, Ritz bounds on the extreme whitened modes, factor conditioning."""
    tick = sync()
    values, M = net(g, g['w'].log()); op = Operator(g, values, M)
    held = draw_probes_noA(g, 32, torch.Generator(device=DEV).manual_seed(seed + 2))
    res = dict(seat=label.seat, q=label.q, held_white=float(energy_error_ref(g, op, held).mean()))
    D, trace, gap, residual = divergence_terms(g, op, trace_dtype=g['ZT'].dtype)
    ge = dict(g); ge.pop('ext', None)
    _, ritz = extreme_terms(ge, op, 40, 8, torch.Generator(device=DEV).manual_seed(seed + 5))
    res.update(divergence_per_mode=float(D) / label.d, trace_per_mode=float(trace) / label.d, logdet_gap=float(gap), solve_residual=residual,
               mu_max_lower=float(ritz.max()), mu_min_upper=float(ritz.min()), **factor_conditioning(op))
    res['spectral_seconds'] = sync() - tick
    return res


def draw_probes_noA(g, white, generator):
    d = g['Rstar'].shape[0]; xi = torch.randn(d, white, dtype=torch.float64, device=DEV, generator=generator)
    return torch.linalg.solve_triangular(g['Rstar'], xi, upper=True)


def energy_error_ref(g, op, z):
    """Energy-metric error on whitened probes without the dense teacher: A z = R*^T (R* z)."""
    Rz = g['Rstar'] @ z; ref = g['Rstar'].T @ Rz; pred = g['data'].quotient(op.apply(g['data'].quotient.lift(z)))
    return torch.linalg.solve_triangular(g['Rstar'].T, pred - ref, upper=False).square().sum(0) / Rz.square().sum(0)


@torch.no_grad()
def evaluate_label(label, g, net, seed):
    """Legacy dense evaluation (materialized A_hat against the dense teacher A): probe metrics, e_A, mechanical directions."""
    tick = sync()
    values, M = net(g, g['w'].log()); op = Operator(g, values, M)
    held = draw_probes(g, 64, 32, torch.Generator(device=DEV).manual_seed(seed + 2))
    e = energy_error(g, op, held)
    res = dict(seat=label.seat, q=label.q, held_energy_error=float(e[:64].mean()), held_coarse=float(e[:32].mean()), held_fine=float(e[32:64].mean()), held_white=float(e[64:].mean()),
               held_dual=float(dual_error(g, op, 32, torch.Generator(device=DEV).manual_seed(seed + 4))[0].mean()))
    A, R = g['A'], g['Rstar']
    Shat = op.materialize(); Ahat, _ = quotient_dense(Shat, g['data'].quotient); del Shat
    _, info = torch.linalg.cholesky_ex(Ahat, upper=True); res['cholesky_info'] = int(info)
    D = Ahat - A; res['schur_relative_error'] = float(torch.linalg.vector_norm(D) / torch.linalg.vector_norm(A))
    off = D.clone(); off.diagonal().zero_(); Aoff = A.clone(); Aoff.diagonal().zero_()
    res['offdiagonal_relative_error'] = float(torch.linalg.vector_norm(off) / torch.linalg.vector_norm(Aoff)); del off, Aoff, D
    fac = V0.LUFactor(Ahat)
    if label.dirs is None:
        x, names, force = make_directions(label.data, label.sample.cache); label.dirs = (x, names, force, DenseUpperFactor(R).solve(force))
    x, names, force, fref = [t.to(DEV) if torch.is_tensor(t) else t for t in label.dirs]
    mech = evaluate(fac, lambda v: A @ v, x, names, force, fref)
    res['groups'] = {k.replace('independent_', 'registered_'): v for k, v in mech['groups'].items()}; res['gaussian_force_summary'] = mech['independent_force_summary']
    def en(xm, xr): return torch.linalg.vector_norm(R @ (xm - xr), dim=0) / torch.linalg.vector_norm(R @ xr, dim=0)
    e_inv = en(fac.solve(A @ x), x)
    res['inverse_energy_norm_rms'] = {grp: float(e_inv[[i for i, nm in enumerate(names) if nm.startswith(grp)]].square().mean().sqrt())
                                      for grp in ('regression/random', 'regression/cos', 'independent_random/', 'independent_smooth/', 'independent_local/')}
    gf = torch.Generator(device=DEV).manual_seed(seed + 3)
    zc = torch.randn(g['P3'].shape[1], 16, dtype=torch.float64, device=DEV, generator=gf)
    f = g['data'].quotient(g['wq'][:, None] * (g['P3'] @ zc)); xr = DenseUpperFactor(R).solve(f); xm = fac.solve(f)
    res['physical_force'] = dict(displacement_energy_norm_rms=float(en(xm, xr).square().mean().sqrt()), compliance_relative_max=float(((f * xm).sum(0) / (f * xr).sum(0) - 1).abs().max()))
    label.dirs = tuple(t.cpu() if torch.is_tensor(t) else t for t in label.dirs)
    del Ahat, fac; torch.cuda.empty_cache()
    res['evaluation_seconds'] = sync() - tick
    return res


def label_d(g): return int(g['d'])


def brief(res):
    out = dict(seat=res['seat'], white=round(res['held_white'], 4))
    if 'held_energy_error' in res: out.update(held=round(res['held_energy_error'], 4), dual=round(res['held_dual'], 4))
    if 'divergence_per_mode' in res:
        out.update(D=round(res['divergence_per_mode'], 5), gap=round(res['logdet_gap'], 2), mu_max=round(res['mu_max_lower'], 3), mu_min=round(res['mu_min_upper'], 4), resid=float('%.1e' % res['solve_residual']), condL=float('%.2e' % (res['L_sigma_max'] / res['L_sigma_min'])), normM=round(res['M_norm'], 3))
    if 'schur_relative_error' in res:
        out.update(eA=round(res['schur_relative_error'], 4), chol=res['cholesky_info'],
                   smooth_E=round(res['groups']['registered_smooth/']['energy_relative_max'], 4), smooth_inv=round(res['inverse_energy_norm_rms']['independent_smooth/'], 3),
                   local_inv=round(res['inverse_energy_norm_rms']['independent_local/'], 3), phys_force=round(res['physical_force']['displacement_energy_norm_rms'], 3),
                   compl=round(res['physical_force']['compliance_relative_max'], 3))
    out['sec'] = round(res['evaluation_seconds'], 1); return out


# ----------------------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--labels', required=True, help='JSON list of records with packet, receipt, reference, trace_cache, seat, split')
    ap.add_argument('--output', required=True); ap.add_argument('--steps', type=int, default=20000); ap.add_argument('--chunk', type=int, default=50)
    ap.add_argument('--eval-every', type=int, default=2000); ap.add_argument('--eval-max-q', type=int, default=23000); ap.add_argument('--eval-labels', type=int, default=3)
    ap.add_argument('--r-near', type=float, default=0.2); ap.add_argument('--decay', type=float, default=0.03); ap.add_argument('--off-scale', type=float, default=OFF_SCALE, help='bound of |L_ij| relative to min(L_ii,L_jj)*exp(-d/decay)')
    ap.add_argument('--rank', type=int, default=512); ap.add_argument('--width', type=int, default=64); ap.add_argument('--hidden', type=int, default=128)
    ap.add_argument('--probes', type=int, default=32); ap.add_argument('--white-probes', type=int, default=32); ap.add_argument('--action-probes', type=int, default=16); ap.add_argument('--action-weight', type=float, default=3.0); ap.add_argument('--dual-weight', type=float, default=1.0); ap.add_argument('--dual-probes', type=int, default=16); ap.add_argument('--dual-start', type=int, default=0); ap.add_argument('--dual-clip', type=float, default=1e4); ap.add_argument('--energy-ramp', type=int, default=3000, help='energy-loss weight ramps linearly from 0 to 1 over this many steps')
    ap.add_argument('--dual-kind', default='white', choices=['white', 'physical']); ap.add_argument('--dual-log', type=int, default=1); ap.add_argument('--compliance-weight', type=float, default=0.0); ap.add_argument('--energy-weight', type=float, default=1.0)
    ap.add_argument('--lr', type=float, default=1e-3); ap.add_argument('--warmup', type=int, default=200); ap.add_argument('--lr-floor', type=float, default=0.1)
    ap.add_argument('--seed', type=int, default=2026091209); ap.add_argument('--init-checkpoint', default=None); ap.add_argument('--max-train-labels', type=int, default=1000); ap.add_argument('--train-max-q', type=int, default=24000)
    ap.add_argument('--aug-prob', type=float, default=0.5, help='probability of a random cube symmetry per step'); ap.add_argument('--volume-width', type=int, default=32)
    ap.add_argument('--tri-solver', default='auto', choices=['auto', 'dense', 'sparse']); ap.add_argument('--dense-max-q', type=int, default=26000, help='auto: dense trsm up to this q, cuSPARSE CSR above')
    ap.add_argument('--divergence-weight', type=float, default=0.0, help='weight of the exact log-det divergence per mode (probe-free objective)')
    ap.add_argument('--extreme-weight', type=float, default=0.0, help='weight of the extreme whitened-mode term'); ap.add_argument('--extreme-block', type=int, default=8); ap.add_argument('--extreme-iters', type=int, default=2)
    ap.add_argument('--trace-dtype', default='float32', choices=['float32', 'float64']); ap.add_argument('--eval-dense', type=int, default=1, help='legacy dense evaluation (materialized A_hat, probe metrics)')
    ap.add_argument('--solve-tol', type=float, default=1e-6, help='rigid-correction solve residual above which a step is treated as ill-conditioned (no extreme term, no rigid log-det term)')
    ap.add_argument('--model', default='net', choices=['net', 'free', 'free_unbounded', 'free_coarse'], help='free: free coefficients under the network head bounds; free_coarse: free band + coarse-space compliance G = exp(H); single label, no augmentation')
    ap.add_argument('--coarse-stride', type=int, default=4); ap.add_argument('--coarse-prune', type=float, default=0.05); ap.add_argument('--coarse-init', default='teacher', choices=['teacher', 'identity'])
    ap.add_argument('--seats', default=None, help='comma-separated seats to train on (subset of the label file)')
    args = ap.parse_args()
    out = Path(args.output); out.mkdir(parents=True, exist_ok=False); t_start = time.perf_counter(); torch.manual_seed(args.seed)
    write_json(out / 'PROTOCOL.json', dict(vars(args), schema='CUTFEM_SUPERELEMENT_V1', script_sha256=V0.sha256(__file__)))
    records = json.load(open(args.labels))
    train_recs = [r for r in records if r['split'] == 'train' and r['q'] <= args.train_max_q][:args.max_train_labels]; val_recs = [r for r in records if r['split'] != 'train' and r['q'] <= args.train_max_q]
    if args.seats:                                                       # explicit seats: trained regardless of split (a known-label diagnostic, recorded as such)
        keep = {int(x) for x in args.seats.split(',')}; train_recs = [r for r in records if int(r['seat']) in keep]; val_recs = []
    if args.model != 'net': assert len(train_recs) == 1 and args.aug_prob == 0, 'free coefficients: one training label, no augmentation'
    print(json.dumps(dict(stage='labels', train=[r['seat'] for r in train_recs], validation=[r['seat'] for r in val_recs])), flush=True)
    labels = {int(r['seat']): Label(r, args.r_near, args.decay, args.off_scale) for r in train_recs + val_recs}
    for l in labels.values(): l.tri_mode = args.tri_solver if args.tri_solver != 'auto' else ('dense' if l.q <= args.dense_max_q else 'sparse')
    print(json.dumps(dict(stage='prepared', seconds=time.perf_counter() - t_start, q={s: l.q for s, l in labels.items()})), flush=True)
    first = labels[int(train_recs[0]['seat'])]
    if args.model == 'free_coarse':
        Pq = first.coarse_basis(args.coarse_stride, args.coarse_prune); net = FreeCoarseModel(first, args.off_scale, Pq.shape[1]).to(DEV)
        print(json.dumps(dict(stage='coarse_basis', stride=args.coarse_stride, prune=args.coarse_prune, columns=int(Pq.shape[1]))), flush=True)
    else:
        net = (FreeCoefficientModel(first, args.rank, args.off_scale) if args.model == 'free' else FreeUnboundedModel(first, args.rank, args.off_scale) if args.model == 'free_unbounded'
               else GeometryNet(first.images.shape[1], args.width, args.rank, args.hidden, off_scale=args.off_scale, volume_width=args.volume_width)).to(DEV)
    group = cube_group()
    if args.model == 'free_coarse':                                        # band from a network checkpoint if given, coarse compliance from the teacher (or identity)
        g0 = first.to_gpu(need_A=False, need_Z=True, z_dtype=torch.float64); log_w0 = g0['w'].log()
        if args.init_checkpoint:
            ref = GeometryNet(first.images.shape[1], args.width, args.rank, args.hidden, off_scale=args.off_scale, volume_width=args.volume_width).to(DEV)
            ref.load_state_dict(torch.load(args.init_checkpoint, map_location='cuda')['net']); ref.eval(); net.from_network(ref, g0); del ref
        with torch.no_grad():
            values0 = bounded_band(net.dg, net.pair_p, g0, log_w0, args.off_scale)
            info = net.init_coarse_from_teacher(g0, values0) if args.coarse_init == 'teacher' else {}
            v_free, M_free = net(g0, log_w0); D0 = divergence_terms(g0, Operator(g0, v_free, M_free), torch.float64)[0] / g0['d']
        check = dict(stage='free_coarse_init', seat=first.seat, checkpoint=args.init_checkpoint, columns=int(g0['Pq'].shape[1]), divergence_per_mode_init=float(D0), **info)
        print(json.dumps(check), flush=True); write_json(out / 'FREE_INIT_CHECK.json', check); del g0, v_free, M_free; first.release(); torch.cuda.empty_cache()
    elif args.init_checkpoint and args.model in ('free', 'free_unbounded'):   # free coefficients start from the network's own prediction for this label (original frame)
        ref = GeometryNet(first.images.shape[1], args.width, 512, args.hidden, off_scale=args.off_scale, volume_width=args.volume_width).to(DEV)
        ref.load_state_dict(torch.load(args.init_checkpoint, map_location='cuda')['net']); ref.eval()
        g0 = first.to_gpu(need_A=False, need_Z=True, z_dtype=torch.float64); log_w0 = g0['w'].log()
        with torch.no_grad():
            net.from_network(ref, g0); v_ref, M_ref = ref(g0, log_w0); v_free, M_free = net(g0, log_w0)
            D_ref = divergence_terms(g0, Operator(g0, v_ref, M_ref), torch.float64)[0] / g0['d']; D_free = divergence_terms(g0, Operator(g0, v_free, M_free), torch.float64)[0] / g0['d']
        check = dict(stage='free_init', seat=first.seat, checkpoint=args.init_checkpoint, values_max_rel_diff=float((v_ref - v_free).abs().max() / v_ref.abs().max()),
                     M_max_rel_diff=float((M_ref[:, :min(M_ref.shape[1], M_free.shape[1])] - M_free[:, :min(M_ref.shape[1], M_free.shape[1])]).abs().max() / M_ref.abs().max()), divergence_per_mode_net=float(D_ref), divergence_per_mode_free=float(D_free))
        print(json.dumps(check), flush=True); write_json(out / 'FREE_INIT_CHECK.json', check); del ref, g0, v_ref, M_ref, v_free, M_free; first.release(); torch.cuda.empty_cache()
    elif args.init_checkpoint: net.load_state_dict(torch.load(args.init_checkpoint, map_location='cuda')['net'])
    nparam = sum(p.numel() for p in net.parameters()); write_json(out / 'MODEL.json', dict(parameters=nparam, model=str(net)))
    print(json.dumps(dict(stage='setup', parameters=nparam)), flush=True)
    opt = torch.optim.Adam(net.parameters(), lr=args.lr)
    gen = torch.Generator(device=DEV).manual_seed(args.seed + 1)
    eval_train = [l for l in labels.values() if (args.seats or l.record['split'] == 'train') and l.q <= args.eval_max_q][:args.eval_labels]
    eval_val = [l for l in labels.values() if not args.seats and l.record['split'] != 'train' and l.q <= args.eval_max_q][:args.eval_labels]
    probe_objective = args.energy_weight > 0 or args.action_weight > 0 or args.dual_weight > 0 or args.compliance_weight > 0
    exact_objective = args.divergence_weight > 0 or args.extreme_weight > 0
    z_dtype = torch.float32 if args.trace_dtype == 'float32' else torch.float64
    def run_eval(step):
        rows = []
        for l in eval_train + eval_val:
            g = l.to_gpu(need_A=False, need_Z=True, z_dtype=torch.float32); res = evaluate_spectral(l, g, net, args.seed)
            del g; l.release(); torch.cuda.empty_cache()
            if args.eval_dense:
                g = l.to_gpu(need_A=True, need_Z=False); res.update(evaluate_label(l, g, net, args.seed)); del g; l.release(); torch.cuda.empty_cache()
            else: res['evaluation_seconds'] = res['spectral_seconds']
            res['step'] = step; res['split'] = l.record['split'] if not args.seats else 'known-label'; rows.append(res)
            print(json.dumps(dict(stage='evaluation', step=step, split=res['split'], **brief(res))), flush=True)
        write_json(out / f'EVALUATION_{step:06d}.json', json_finite(rows)); return rows
    evaluations = [run_eval(0)]
    step = 0; order = list(labels[int(r['seat'])] for r in train_recs); rng = np.random.default_rng(args.seed)
    history = []
    while step < args.steps:
        rng.shuffle(order)
        for l in order:
            if step >= args.steps: break
            g = l.to_gpu(need_A=probe_objective, need_Z=exact_objective, z_dtype=z_dtype); log_w = g['w'].log()
            for _ in range(args.chunk):
                if step >= args.steps: break
                step += 1; tick = sync()
                sched = min(1.0, step / args.warmup) * (args.lr_floor + (1 - args.lr_floor) * 0.5 * (1 + math.cos(math.pi * (step - 1) / max(args.steps - 1, 1))))
                for g_ in opt.param_groups: g_['lr'] = args.lr * sched
                opt.zero_grad(set_to_none=True)
                try:
                    if args.aug_prob > 0 and rng.random() < args.aug_prob:
                        perm, sign = group[int(rng.integers(1, len(group)))]
                        ga = dict(g); ga.update(l.transformed(perm, sign))
                    else: ga = g
                    values, M = net(ga, log_w); op = Operator(ga, values, M)
                    loss_e = loss_a = loss_d = loss_c = loss_D = loss_x = torch.zeros((), dtype=torch.float64, device=DEV); ritz = None
                    if args.energy_weight > 0:
                        z = draw_probes(g, args.probes, args.white_probes, gen); loss_e = energy_error(g, op, z).mean()
                    if args.action_weight > 0:
                        zw = torch.randn(g['A'].shape[0], args.action_probes, dtype=torch.float64, device=DEV, generator=gen); loss_a = action_error(g, op, zw).mean()
                    residual = 0.0
                    if args.divergence_weight > 0:
                        D, trace, gap, residual = divergence_terms(g, op, z_dtype, args.solve_tol); loss_D = D / g['d']
                    if args.extreme_weight > 0 and residual <= args.solve_tol:
                        loss_x, ritz = extreme_terms(g, op, args.extreme_iters, args.extreme_block, gen)
                    if args.dual_weight > 0 and step >= args.dual_start:
                        e_disp, e_comp = dual_error(g, op, args.dual_probes, gen, kind=args.dual_kind)
                        loss_d = (torch.log1p(e_disp) if args.dual_log else e_disp.clamp(max=args.dual_clip)).mean()
                        loss_c = e_comp.clamp(max=args.dual_clip).mean()
                except torch._C._LinAlgError as err:
                    print(json.dumps(dict(stage='guard', step=step, seat=l.seat, reason=repr(err)[:120])), flush=True); continue
                w_e = min(1.0, step / max(args.energy_ramp, 1))
                loss = args.energy_weight * w_e * loss_e + args.action_weight * loss_a + args.dual_weight * loss_d + args.compliance_weight * loss_c + args.divergence_weight * loss_D + args.extreme_weight * loss_x
                if not torch.isfinite(loss):
                    print(json.dumps(dict(stage='guard', step=step, seat=l.seat)), flush=True); continue
                loss.backward(); gn = torch.nn.utils.clip_grad_norm_(net.parameters(), 10.0)
                if not torch.isfinite(gn):
                    opt.zero_grad(set_to_none=True); print(json.dumps(dict(stage='guard', step=step, seat=l.seat, reason='nonfinite gradient')), flush=True); continue
                opt.step()
                row = dict(step=step, seat=l.seat, lr=args.lr * sched, loss=float(loss.detach()), energy_loss=float(loss_e.detach()), action_loss=float(loss_a.detach()), dual_loss=float(loss_d.detach()), compliance_loss=float(loss_c.detach()), grad_norm=float(gn), seconds=sync() - tick)
                if args.divergence_weight > 0: row.update(divergence_per_mode=float(loss_D.detach()), trace_per_mode=float(trace.detach()) / label_d(g), logdet_gap=float(gap.detach()), solve_residual=residual, ill_conditioned=int(residual > args.solve_tol), augmented=int(ga is not g))
                if ritz is not None: row.update(extreme_loss=float(loss_x.detach()), ritz_max=float(ritz.detach().max()), ritz_min=float(ritz.detach().min()))
                history.append(row); append_json(out / 'HISTORY.jsonl', row)
                if step <= 5 or step % 50 == 0:
                    print(json.dumps(dict(**row, mean_loss_200=float(np.mean([r['loss'] for r in history[-200:]])), elapsed=time.perf_counter() - t_start, peak_gib=torch.cuda.max_memory_allocated() / 2**30)), flush=True)
                if step % args.eval_every == 0 or step == args.steps:
                    torch.save(dict(net=net.state_dict(), step=step), out / f'CHECKPOINT_{step:06d}.pt')
                    l.store_extremes(g); del g, op, values, M; l.release(); torch.cuda.empty_cache()
                    evaluations.append(run_eval(step))
                    g = l.to_gpu(need_A=probe_objective, need_Z=exact_objective, z_dtype=z_dtype); log_w = g['w'].log()
            l.store_extremes(g); del g; l.release(); torch.cuda.empty_cache()
    write_json(out / 'RESULT.json', json_finite(dict(status='COMPLETED_FIXED_BUDGET', steps=args.steps, elapsed_seconds=time.perf_counter() - t_start, parameters=nparam,
                                                    peak_gpu_allocated_gib=torch.cuda.max_memory_allocated() / 2**30, initial=evaluations[0], final=evaluations[-1])))
    print(json.dumps(dict(stage='done', elapsed=time.perf_counter() - t_start)), flush=True)


if __name__ == '__main__':
    main()
